package com.example.minion_project;

import androidx.fragment.app.Fragment;

import com.example.minion_project.user.User;
import com.example.minion_project.user.UserAttendingFragment;

import java.util.ArrayList;
import java.util.UUID;

public class Event {
    private String eventID;
    private String eventDate;
    private String eventName;
    private String eventDescription;
    private String eventCapacity;
    private String eventOrganizer;
    private ArrayList<User> eventAttendees;
    private ArrayList<User> eventWaitlist;
    private ArrayList<User> eventInvited;
    private ArrayList<User> eventCanceled;
    private String eventDetails;
    private String eventTime;
    private String eventImage;
    private String eventLocation;

    public ArrayList<User> getEventInvited() {
        return eventInvited;
    }

    public void setEventInvited(ArrayList<User> eventInvited) {
        this.eventInvited = eventInvited;
    }

    public ArrayList<User> getEventCanceled() {
        return eventCanceled;
    }

    public void setEventCanceled(ArrayList<User> eventCanceled) {
        this.eventCanceled = eventCanceled;
    }

    /**
     * We have arrays for invited, canceled, waitlist and attendees
     */
    public Event() {

        this.eventID = ""; // this is generated by firebase so we dont need UUID.randomUUID()
        this.eventDate = "";
        this.eventName = "";
        this.eventDescription = "";
        this.eventCapacity = "";
        this.eventOrganizer = null;
        this.eventAttendees = new ArrayList<>();
        this.eventWaitlist = new ArrayList<>();
        this.eventInvited = new ArrayList<>();
        this.eventCanceled = new ArrayList<>();
        this.eventImage = "";
        this.eventLocation = "";

    }

    // Parameterized constructor
    public Event(String eventId,String eventDate, String eventName, String eventDescription, String eventCapacity,
                 ArrayList<User> waitlist, ArrayList<User> participants, String eventOrganizer, String eventImage) {
        this.eventID = eventId;
        this.eventDate = eventDate;
        this.eventName = eventName;
        this.eventDescription = eventDescription;
        this.eventCapacity = eventCapacity;
        this.eventOrganizer = eventOrganizer;
        this.eventImage = eventImage;

        // If participants and waitlist are null, initialize them to empty lists
        this.eventAttendees = (participants != null) ? participants : new ArrayList<>();
        this.eventWaitlist = (waitlist != null) ? waitlist : new ArrayList<>();
    }

    public String getEventID() {
        return eventID;
    }
    public String getEventImage() { return eventImage;}
    public void setEventImage(String eventImage){
        this.eventImage = eventImage;
    }

    public void setEventID(String eventID) {
        this.eventID = eventID;
    }

    public String getEventDate() {
        return eventDate;
    }

    public void setEventDate(String eventDate) {
        this.eventDate = eventDate;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public String getEventDescription() {
        return eventDescription;
    }

    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    public String getEventCapacity() {
        return eventCapacity;
    }

    public void setEventCapacity(String eventCapacity) {
        this.eventCapacity = eventCapacity;
    }

    public String getEventOrganizer() {
        return eventOrganizer;
    }

    public void setEventOrganizer(String eventOrganizer) {
        this.eventOrganizer = eventOrganizer;
    }

    public ArrayList<User> getEventAttendees() {
        return eventAttendees;
    }

    public void setEventAttendees(ArrayList<User> eventAttendees) {
        this.eventAttendees = eventAttendees;
    }

    public ArrayList<User> getEventWaitlist() {
        return eventWaitlist;
    }

    public void setEventWaitlist(ArrayList<User> eventWaitlist) {
        this.eventWaitlist = eventWaitlist;
    }

    public String getEventDetails() {
        return eventDetails;
    }

    public void setEventDetails(String eventDetails) {
        this.eventDetails = eventDetails;
    }

    public String getEventTime() {
        return eventTime;
    }

    public void setEventTime(String eventTime) {
        this.eventTime = eventTime;
    }

    public String getEventLocation() {
        return eventLocation;
    }

    public void setEventLocation(String eventLocation) {
        this.eventLocation = eventLocation;
    }
}